puts "I HAD TO CANCEL A VERY IMPORTANT BUSINESS MEETING FOR THIS! WHADDYA WANT, YA DINGUS?!"
answer = gets.chomp
puts "WHADDYA MEAN \"" + answer.upcase + "\"? YOU AIN'T GETTIN' NOTHIN'! YOU'RE FIRED! AAAAAHHHH!!H!H!!111!!1eleven!!"
